export default [
  {
    title: "2021-09-16",
    data: [
      {
        id: 1,
        name: "Mr. Emma Obi",
        AV: "EA",
        category: "Pos-Atm",
        type: "Debit",
        status: "sent",
        reciever: "",
        amount: 5000.0,
        date: "12-02-22",
      },
      {
        id: 2,
        name: "John Philips",
        AV: "JP",
        category: "Tv-Payment",
        status: "sent",
        reciever: "",
        type: "Debit",
        status: "sent",
        amount: 16500.0,
        date: "1-03-22",
      },
    ],
  },
  {
    title: "2021-07-08",
    data: [
      {
        id: 1,
        name: "Donald Ben",
        category: "Pos-Atm",
        AV: "DB",
        type: "Debit",
        status: "sent",
        reciever: "",
        amount: 1000.0,
        date: "12-02-22",
      },
      {
        id: 2,
        name: "Evans Maduka",
        category: "Tv-Payment",
        AV: "EM",
        status: "sent",
        reciever: "",
        type: "Debit",
        status: "sent",
        amount: 250000.0,
        date: "1-03-22",
      },
    ],
  },
  {
    title: "2021-06-26",
    data: [
      {
        id: 3,
        name: "Mrs. Henry Gold",
        category: "Received Money",
        AV: "HG",
        reciever: "",
        type: "Credit",
        status: "recieved",
        amount: 500000.0,
        date: "12-02-22",
      },
      {
        id: 4,

        name: "Global limited",
        category: "Electronics",
        AV: "G",
        status: "sent",
        reciever: "",
        type: "Debit",
        status: "sent",
        amount: 2000.0,
        date: "1-03-22",
      },
    ],
  },
  {
    title: "2021-06-25",
    data: [
      {
        id: 3,
        name: "Mrs. Maureen Luke",
        category: "",
        AV: "ML",
        reciever: "",
        type: "Credit",
        status: "recieved",
        amount: 10000.0,
        date: "12-02-22",
      },
      {
        id: 4,

        name: "Maru Kombat",
        category: "Electronics",
        AV: "MK",
        status: "sent",
        reciever: "",
        type: "Debit",
        status: "sent",
        amount: 50000.0,
        date: "1-03-22",
      },
    ],
  },
];
